Animal data access
DouglasNeuroInformatics/Douglas_User_Documentation pull request #15
Opened 2021-07-23 17:08 UTC by jeremie-fouquet

This pull request partly resolves #13.

2021-07-29 14:23 UTC, gdevenyi requested changes

2021-07-29 14:23 UTC, gdevenyi commented on docs/doing_things/index.md
> +## <a name="systemAccess"></a>Accessing the System
There's no need for adding anchors, they're auto-generated by sphinx.

2021-07-29 14:23 UTC, gdevenyi commented on docs/doing_things/index.md
> +## <a name="dataTransfer"></a>Transferring Data
Ditto

2021-07-29 14:23 UTC, gdevenyi commented on docs/doing_things/index.md
> +Conversion to other formats (dicom and nifti) is available upon request.
DICOM and NIFTI

2021-07-29 14:23 UTC, gdevenyi commented on docs/doing_things/index.md
> +accessing the bruker7t computer. The [tools for data transfer](#dataTransfer) will
You can link to the auto-generated section anchors like the example here
https://github.com/DouglasNeuroInformatics/Douglas_User_Documentation/blob/master/docs/about_the_platform/index.md?plain=1#L28

Doc ref:
https://myst-parser.readthedocs.io/en/v0.15.1/sphinx/use.html#automatically-create-targets-for-section-headers

2021-07-29 16:51 UTC, merged

2021-07-29 16:51 UTC, gdevenyi commented
Cheers thanks!

2021-08-04 15:28 UTC, surchs commented
@all-contributors please add @jeremie-fouquet for content, doc