Add data sharing
DouglasNeuroInformatics/Douglas_User_Documentation pull request #29
Opened 2021-08-05 16:47 UTC by surchs

Draft for data sharing docs

2021-08-05 18:01 UTC, surchs commented
@isabelbacellar, do you maybe have some feedback on this?

2021-08-05 19:00 UTC, gdevenyi commented
@surchs can you possibly use proper inline-references for the links and such? I think we might be able to auto-generate a "all links" appendix webpage if we go about doing it that way.

2021-08-05 19:03 UTC, gdevenyi requested changes

2021-08-05 19:03 UTC, gdevenyi commented on docs/conf.py
> +
I was working on this and I thought I added it somewhere hrmmm

2021-08-05 19:03 UTC, gdevenyi commented on docs/conf.py
> +    "sphinx.ext.todo"
This is cool, how does it work?

2021-08-05 19:06 UTC, surchs commented on docs/conf.py
> +    "sphinx.ext.todo"
It allows you to generate the docs with TODO boxes and to keep TODO boxes in the text as reminders of future fixes: https://www.sphinx-doc.org/en/master/usage/extensions/todo.html

2021-08-05 19:07 UTC, surchs commented on docs/conf.py
> +
Do you mean you had already pushed this? I didn't see a conflict before my PR

2021-08-05 19:07 UTC, surchs commented
> @surchs can you possibly use proper inline-references for the links and such? I think we might be able to auto-generate a "all links" appendix webpage if we go about doing it that way.

Hey @gdevenyi, can you explain what you mean by this? Or comment inside of a file where the link is not used the way you suggest? Not sure exactly what the difference is you are referring to

2021-08-05 19:48 UTC, gdevenyi commented
https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#footnotes

2021-08-05 19:56 UTC, surchs commented
Those are footnotes, I'm not using them. I use links to link to outside resources. Sphinx also has a glossary for term definitions. Are you saying the outside resources should be footnotes?

2021-08-05 20:02 UTC, gdevenyi commented
Right they call it that but that mixes two concepts together in typography.

I was hoping there might be a plugin that we can use to aggregate all external links into a seperate resources page.

I haven't searched deeply enough to confirm.

2021-08-05 20:15 UTC, surchs commented
Yeah I see. That might be possible, I haven't seen it yet. Sphinx by default uses RST and there are some syntax mixings going on here because MyST is markdown. So maybe there are additional options to be discovered. 

But for now, is there anything you want to change about the way markdown links are set in this PR?

2021-08-06 15:39 UTC, isabelbacellar commented
> @isabelbacellar, do you maybe have some feedback on this?

@surchs amazing work! 🏆 Just a few general comments:

1. "Although making your work accessible to others involves costs (effort and time, mostly), it considerably increases the reach of your work and thus also benefits your academic career." >> Say that this process will be a lot smoother if you plan for sharing from day 1 (i.e. keep your data structured and organized, figure our ethics/DMP beforehand etc). I think that's an important point because part of the DNP's goal is to help people manage well their data on a daily basis.

2. "Your first step should be to ensure that you can in fact share the raw or derivative data you intend to share. Here are some reasons you may be constrained in your ability to share your data:" >> I would just note that "constraints" don't necessarily mean abandoning data sharing plans, but sometimes just adapting to what's possible (e.g. sharing less/part, use anonymization methods etc).

3. Perhaps warn that sharing data through journals may create copyright issues. 

4. Finally, if you're not covering it elsewhere, maybe mention from a technical point of view how using the platform may make data sharing easier (e.g. something about transferring the data, if applicable).

2021-08-06 16:45 UTC, gdevenyi commented
@surchs 
> But for now, is there anything you want to change about the way markdown links are set in this PR?

After a bunch of searching it seems the only solution right now otherwise is to go to full citations, which is way too much work, so the current format is fine :+1:

2021-08-06 17:30 UTC, surchs commented
Thanks @isabelbacellar for the feedback!

> "Although making your work accessible to others involves costs (effort and time, mostly), it considerably increases the reach of your work and thus also benefits your academic career." >> Say that this process will be a lot smoother if you plan for sharing from day 1 (i.e. keep your data structured and organized, figure our ethics/DMP beforehand etc). I think that's an important point because part of the DNP's goal is to help people manage well their data on a daily basis.

> "Your first step should be to ensure that you can in fact share the raw or derivative data you intend to share. Here are some reasons you may be constrained in your ability to share your data:" >> I would just note that "constraints" don't necessarily mean abandoning data sharing plans,Finally, if you're not covering it elsewhere, maybe mention from a technical point of view how using the platform may make data sharing easier (e.g. something about transferring the data, if applicable). but sometimes just adapting to what's possible (e.g. sharing less/part, use anonymization methods etc).
EDIT: or restricting access to shared datasets (e.g. requiring users to be PIs)

I tried to address the first two points in the commits. Does that answer your points?

> Perhaps warn that sharing data through journals may create copyright issues.

This is a good idea. Do you have a good source that I can link to here, I am not intimately familiar with these concerns.

> Finally, if you're not covering it elsewhere, maybe mention from a technical point of view how using the platform may make data sharing easier (e.g. something about transferring the data, if applicable).

I think this is an important point that we should cover somewhere. At the moment, the technical solutions we offer revolve around the ability to store data, not how you store it. I.e.: we give people space on a managed hard-drive but don't tell them how to use it. The solutions we offer for research methods such as data sharing are your and our expertise on the matter, documentation, and training. But they are not technical solutions or mandates. Gabe has set up some documents to discuss these points in the next meeting (I'll be in Europe then).

@all-contributors please add @isabelbacellar for review

2021-08-06 17:31 UTC, surchs commented
@gdevenyi thanks are you OK with merging this as is then?

@all-contributors please add @gdevenyi for review

2021-08-06 17:42 UTC, isabelbacellar commented
> Thanks @isabelbacellar for the feedback!
> 
> > "Although making your work accessible to others involves costs (effort and time, mostly), it considerably increases the reach of your work and thus also benefits your academic career." >> Say that this process will be a lot smoother if you plan for sharing from day 1 (i.e. keep your data structured and organized, figure our ethics/DMP beforehand etc). I think that's an important point because part of the DNP's goal is to help people manage well their data on a daily basis.
> 
> > "Your first step should be to ensure that you can in fact share the raw or derivative data you intend to share. Here are some reasons you may be constrained in your ability to share your data:" >> I would just note that "constraints" don't necessarily mean abandoning data sharing plans,Finally, if you're not covering it elsewhere, maybe mention from a technical point of view how using the platform may make data sharing easier (e.g. something about transferring the data, if applicable). but sometimes just adapting to what's possible (e.g. sharing less/part, use anonymization methods etc).
> > EDIT: or restricting access to shared datasets (e.g. requiring users to be PIs)
> 
> I tried to address the first two points in the commits. Does that answer your points?
> 
> > Perhaps warn that sharing data through journals may create copyright issues.
> 
> This is a good idea. Do you have a good source that I can link to here, I am not intimately familiar with these concerns.
> 
> > Finally, if you're not covering it elsewhere, maybe mention from a technical point of view how using the platform may make data sharing easier (e.g. something about transferring the data, if applicable).
> 
> I think this is an important point that we should cover somewhere. At the moment, the technical solutions we offer revolve around the ability to store data, not how you store it. I.e.: we give people space on a managed hard-drive but don't tell them how to use it. The solutions we offer for research methods such as data sharing are your and our expertise on the matter, documentation, and training. But they are not technical solutions or mandates. Gabe has set up some documents to discuss these points in the next meeting (I'll be in Europe then).
> 
> @all-contributors please add @isabelbacellar for review

@surchs for 1+2, I think it's good. When can add more details about 2 (anonymization etc.) in the future, perhaps creating a dedicated page for that. But for now (i.e. a general data sharing page), I think it's enough. As for 3, I learned about that in [this presentation](https://msss365.sharepoint.com/:b:/r/teams/GroupedesoutienCentrederecherche/Shared%20Documents/Open%20Science/OPEN%20SCIENCE/3.06%20OS%20support%20tools%20and%20services%20(and%20case%20studies)/The%20Future%20is%20Open%20-%20Becoming%20an%20Open%20Researcher.pdf?csf=1&web=1&e=CcOTRa), slide 47. During the webinar they said that this applied for data shared through supplementary materials. Finally, as for point 4, we can surely discuss it later and also update it later, if we don't have any solutions for now.

2021-08-06 19:13 UTC, surchs commented
Thanks @isabelbacellar!
I think the bot is confused here!

2021-08-06 19:17 UTC, gdevenyi commented on docs/conf.py
> +
I thought I had but I can't find anything so :+1:

2021-08-06 19:24 UTC, gdevenyi requested changes

2021-08-06 19:24 UTC, gdevenyi commented on docs/research_methods/sharing_data.md
> +the [**F**indable **A**ccessible **I**nteroperable **R**eusable principles](https://www.go-fair.org/fair-principles/)
I think maybe have the acronym by itself as well.

2021-08-06 19:24 UTC, gdevenyi commented on docs/research_methods/sharing_data.md
> +The main difference between these two options is that option 2. is a specification of 1.
> specification

I'm not sure that's the right word here, but I'm not sure what you're trying to say

2021-08-06 19:24 UTC, gdevenyi commented on docs/research_methods/sharing_data.md
> +  - Some analyses steps take too long or require too many resources for a reader to reasonably re-run them
Or be too large?

2021-08-06 19:24 UTC, gdevenyi commented
I added a few small comments, otherwise good to go :+1:

2021-08-06 19:35 UTC, isabelbacellar commented on docs/research_methods/sharing_data.md
> +The main difference between these two options is that option 2. is a specification of 1.
special case?

2021-08-06 19:44 UTC, surchs commented
OK, thanks both! Incorporated your feedback. I'll go ahead and merge this now!

2021-08-06 19:44 UTC, surchs commented
@all-contributors please add @isabelbacellar for review

2021-08-06 19:45 UTC, merged

2021-08-06 20:03 UTC, isabelbacellar commented
Great work! I'm super happy with this page!!

Just a few small things:

1. "a requirement by funding agencies **and if your group**. If your group"" >> remove bold part.
2. "Slides by McGill on data sharing constraint considerations" > those slides are from the FRQ.
3. Section "To prepare your data for sharing, you should:" >> some items are in lower case, but not others. Also some items are actionable steps and others are links. It breaks the flow of the text a little bit. Perhaps write "Additional resources:" or "Check/See:" before the links?

2021-08-06 20:06 UTC, surchs commented
Ah, thanks @isabelbacellar, good catch. 
Do you maybe want to attempt a pull request to fix these? No problem if not, I can get to that when I'm back

2021-08-06 20:16 UTC, isabelbacellar commented
@surchs I definitely would like to learn, but could we leave it for next time? :) I have to get back to a few other tasks still today

2021-08-11 20:00 UTC, gdevenyi commented
@isabelbacellar you can go here:
https://github.com/DouglasNeuroInformatics/Douglas_User_Documentation/edit/master/docs/research_methods/sharing_data.md

and perform your suggested edits on the document, and then at the bottom select the second option "Create a new branch for this commit and start a pull request." which will kick off this process for your proposed changes for us to discuss.

2021-08-11 21:17 UTC, gdevenyi commented
WOW. Vs-code in a browser window. Mind. Blown.