add docs for running docker as non-root
DouglasNeuroInformatics/Douglas_User_Documentation pull request #59
Opened 2022-10-25 14:25 UTC by joshunrau

2022-10-25 18:24 UTC, gdevenyi requested changes

2022-10-25 18:24 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +    $ dockerd-rootless-setuptool.sh install
All inline code needs markdown codefencing
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

2022-10-25 18:24 UTC, gdevenyi commented on docs/using_the_system/index.md
> +running_docker.md
This should probably be a subheading somewhere, not top-level.

2022-10-25 18:24 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +    $ printf "{\"data-root\": \"%s\"}\n" $DOCKER_DATA_ROOT > .config/docker/daemon.json
codefencing again

2022-10-25 18:24 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +This is set in the file `.config/docker/daemon.json`, which for a new user should not exist. If it does exist, adjust the following procedure as needed. Otherwise, we can create a new directory in `/
we need a callout box here to clarify that `/scratch` only exists on the local system you're using.

2022-10-25 18:24 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +    $ systemctl --user stop docker
fencing

2022-10-25 18:24 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +    $ systemctl --user start docker
fencing

2022-10-26 16:26 UTC, joshunrau commented on docs/using_the_system/running_docker.md
> +    $ dockerd-rootless-setuptool.sh install
aba514d9e7d62dd9f68c308425e17d3faa8f2e20

2022-10-26 17:05 UTC, joshunrau commented on docs/using_the_system/running_docker.md
> +    $ printf "{\"data-root\": \"%s\"}\n" $DOCKER_DATA_ROOT > .config/docker/daemon.json
aba514d9e7d62dd9f68c308425e17d3faa8f2e20

2022-10-26 19:46 UTC, joshunrau commented on docs/using_the_system/running_docker.md
> +This is set in the file `.config/docker/daemon.json`, which for a new user should not exist. If it does exist, adjust the following procedure as needed. Otherwise, we can create a new directory in `/
4c9acd593c7409f48415a49d04de841301f60a60

2022-10-26 19:53 UTC, gdevenyi requested changes

2022-10-26 19:53 UTC, gdevenyi commented on docs/getting_help/index.md
> +contacting us for help, it is important to fully explain the problem you're having, this means explaining:
this violates the "PRs should only be about one thing" but this is simple enough I don't care today.

In the future, separate PRs for separate topics. Good separate Commit at least :+1:

2022-10-26 19:53 UTC, gdevenyi commented on docs/using_the_system/index.md
> +running_docker.md
I'd rather this not go in the sidebar at all then until the PR.

2022-10-26 19:53 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +```
This should be closer to where /scratch is used in the docs.

2022-10-26 19:53 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +Then, using the following command, you can pull the tutorial image, specifying the flags `-d` to run the container in detached mode (i.e., in the background), and `-p` to map port 80 of the container
"The tutorial image"?

Can we maybe replace this with the docker hello-world example?

2022-10-26 20:00 UTC, joshunrau commented on docs/using_the_system/index.md
> +running_docker.md
463172eb7086bf46346a7a0fe564bb4ce9280765

2022-10-26 20:01 UTC, joshunrau commented on docs/getting_help/index.md
> +contacting us for help, it is important to fully explain the problem you're having, this means explaining:
Okay good to know. Will do in the future. Thanks

2022-10-26 20:06 UTC, joshunrau commented on docs/using_the_system/running_docker.md
> +Then, using the following command, you can pull the tutorial image, specifying the flags `-d` to run the container in detached mode (i.e., in the background), and `-p` to map port 80 of the container
8a028a72b25ba16dba7ed4cf336fc16fba94e3ba

2022-10-26 20:09 UTC, joshunrau commented on docs/using_the_system/running_docker.md
> +```
I need to take the new file out of the PR otherwise it will fail your tests as there is a warning issued

2022-10-26 20:15 UTC, gdevenyi requested changes

2022-10-26 20:15 UTC, gdevenyi commented on docs/using_the_system/index.md
> +access_to_software.md
I messed up and confused this with the top level index. It should go here. Please re add.

2022-10-26 20:15 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +```
See other comment, it should be in the index, I mixed things up.

2022-10-26 20:15 UTC, gdevenyi commented on docs/using_the_system/running_docker.md
> +```
I'd still like the admonition to be moved further up.

2022-10-26 20:17 UTC, joshunrau commented on docs/using_the_system/index.md
> +access_to_software.md
I readded it

2022-10-26 20:21 UTC, joshunrau commented on docs/using_the_system/running_docker.md
> +```
99ba762a08cea57fb43fb0c5d236ebf7c4793c97

2022-10-27 13:57 UTC, merged